name: Run mypy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mypy
          # Если используется poetry
          # pip install poetry && poetry install --no-root

          # Если используется requirements.txt
          # pip install -r requirements.txt

      - name: Run mypy
        run: |
          python -m mypy .
